version: "3.8"
networks:
  app-tier:
    driver: bridge
services:
  db:
    image: mysql:8.0
    container_name: genesis_db
    restart: always
    env_file:
      - ./.env
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0 --explicit_defaults_for_timestamp
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - app-tier

  adminer:
    image: adminer
    container_name: genesis_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-tier

  api:
    container_name: genesis_api
    stdin_open: true
    tty: true
    restart: always
    build: .
    ports:
      - 5555:5555
    volumes:
      - ./App:/genesis_api/App
    networks:
      - app-tier

  redis_rate_limiting:
    restart: always
    image: "redis"
    container_name: redis_rate_limiting
    ports:
      - "6379:6379"
    networks:
      - app-tier

  redis_sessions:
    restart: always
    image: "redis"
    container_name: redis_sessions
    ports:
      - "6380:6379"
    networks:
      - app-tier
