FROM python:3.11-bullseye

# Set the working directory in the container to /SmartUP
WORKDIR /api-getway

# Copy all necessary files
COPY . .

# Install all dependencies
RUN pip install -r requirements.txt

# Set environment variables
ENV FLASK_DEBUG=development \
    DEBUG=true \
    DISPLAY=:99

# Run the command to start your application
CMD [ "python", "-m", "flask", "run", "--host=0.0.0.0"]

# Expose port 5555
EXPOSE 5555
