SET NAMES utf8;

SET time_zone = '+00:00';

SET foreign_key_checks = 0;

SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `ML_DIAGNOSTIC`;

CREATE TABLE
    `ML_DIAGNOSTIC` (
        `ID` int NOT NULL AUTO_INCREMENT,
        `SICKNESS` varchar(255) NOT NULL,
        `DESCRIPTION` varchar(255) NOT NULL,
        `PRECISION` double NOT NULL,
        `STATUS` tinyint NOT NULL,
        `CREATION_DATE` date NOT NULL,
        `LAST_UPDATE` timestamp NOT NULL,
        PRIMARY KEY (`ID`),
        KEY `SICKNESS` (`SICKNESS`)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `USER_IMAGE_ML_DIAGNOSTIC_ASSOCIATION`;

CREATE TABLE
    `USER_IMAGE_ML_DIAGNOSTIC_ASSOCIATION` (
        `ID` int NOT NULL AUTO_INCREMENT,
        `USER_IMAGE` int NOT NULL,
        `ML_DIAGNOSTIC` int NOT NULL,
        PRIMARY KEY (`ID`),
        KEY `USER_IMAGE` (`USER_IMAGE`),
        KEY `ML_DIAGNOSTIC` (`ML_DIAGNOSTIC`),
        CONSTRAINT `USER_IMAGE_ML_DIAGNOSTIC_ASSOCIATION_ibfk_1` FOREIGN KEY (`USER_IMAGE`) REFERENCES `USER_IMAGE` (`ID`),
        CONSTRAINT `USER_IMAGE_ML_DIAGNOSTIC_ASSOCIATION_ibfk_2` FOREIGN KEY (`ML_DIAGNOSTIC`) REFERENCES `ML_DIAGNOSTIC` (`ID`)
    ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- 2023-10-14 00:10:28